/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presetacion.cliente;

import entidades.cuenta.RealCuenta;
import entidades.movimiento.Movimiento;
import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import logica.Flogica;

/**
 *
 * @author adriana
 */
public class FrmPrincipalCliente extends javax.swing.JFrame {

    RealCuenta cuenta;
    ArrayList<Movimiento> movimientos;
    JPanel panel_list_movimientos;

    /**
     * Creates new form FrmPrincipalCliente
     */
    public FrmPrincipalCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setLayout(null);
        panel_list_movimientos = new JPanel(new FlowLayout(FlowLayout.LEFT));
        panel_list_movimientos.setLayout(new BoxLayout(panel_list_movimientos, BoxLayout.Y_AXIS));
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    public void set_datos(RealCuenta cuenta) {

        movimientos = cuenta.getMovimientos();
        Iterator<Movimiento> itera = movimientos.iterator();
        while (itera.hasNext()) {
            Movimiento movimiento = itera.next();
            String tipo = Flogica.getInstance().getMovimiento_descripcion(movimiento.getCodigo_tipo_movimiento());

            String signo = (tipo.compareTo("Retiro") == 0) ? "-" : "+";

            panel_list_movimientos.add(new PanelMovimiento(movimiento.getFecha(), movimiento.getImporte(), tipo, signo));
        }
        this.scrolPanel.setViewportView(panel_list_movimientos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_movimientos = new javax.swing.JPanel();
        scrolPanel = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panel_movimientosLayout = new javax.swing.GroupLayout(panel_movimientos);
        panel_movimientos.setLayout(panel_movimientosLayout);
        panel_movimientosLayout.setHorizontalGroup(
            panel_movimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrolPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
        );
        panel_movimientosLayout.setVerticalGroup(
            panel_movimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 702, Short.MAX_VALUE)
                .addComponent(panel_movimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_movimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel_movimientos;
    private javax.swing.JScrollPane scrolPanel;
    // End of variables declaration//GEN-END:variables
}
