/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.cliente;

import entidades.ProxyCuenta;
import entidades.cuenta.RealCuenta;
import entidades.movimiento.Movimiento;
import java.awt.FlowLayout;
import java.net.Proxy;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import logica.Flogica;
import presentacion.FormOperacion;

/**
 *
 * @author adriana
 */
public class FrmPrincipalCliente extends javax.swing.JFrame {

    RealCuenta cuenta;
    ProxyCuenta pcuenta;
    ArrayList<Movimiento> movimientos;
    JPanel panel_list_movimientos;

    /**
     * Creates new form FrmPrincipalCliente
     */
    public FrmPrincipalCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setLayout(null);
        panel_list_movimientos = new JPanel(new FlowLayout(FlowLayout.LEFT));
        panel_list_movimientos.setLayout(new BoxLayout(panel_list_movimientos, BoxLayout.Y_AXIS));
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    public void set_datos(ProxyCuenta pcuenta) {
        this.panel_list_movimientos.removeAll();        
        this.pcuenta=pcuenta;
        this.cuenta=pcuenta.getCuenta();
        this.lbl_nombre_cliente.setText(cuenta.getCliente().getNombreCompleto());
        this.lbl_numero_cuenta.setText(cuenta.getCodigo());
        this.txt_sado.setText(cuenta.getSaldo() + " " + cuenta.getMoneda().getDescripcion());
        this.lbl_sucursal.setText(cuenta.getSucursal().getNombre());
        this.lbl_direcion.setText(cuenta.getSucursal().getCiudad());
        movimientos = cuenta.getMovimientos();
        Collections.reverse(movimientos);
        Iterator<Movimiento> itera = movimientos.iterator();        
        while (itera.hasNext()) {
            Movimiento movimiento = itera.next();
            String tipo = Flogica.getInstance().getMovimiento_descripcion(movimiento.getCodigo_tipo_movimiento());

            String signo = (tipo.compareTo("Retiro") == 0) ? "-" : "+";

            panel_list_movimientos.add(new PanelMovimiento(movimiento.getFecha(), movimiento.getImporte(), tipo, signo));
        }
        this.scrolPanel.setViewportView(panel_list_movimientos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_movimientos = new javax.swing.JPanel();
        scrolPanel = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        lbl_nombre_cliente = new javax.swing.JLabel();
        lbl_numero_cuenta = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        txt_sado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbl_sucursal = new javax.swing.JLabel();
        lbl_direcion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(951, 538));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("Histoiral de movimientos");

        javax.swing.GroupLayout panel_movimientosLayout = new javax.swing.GroupLayout(panel_movimientos);
        panel_movimientos.setLayout(panel_movimientosLayout);
        panel_movimientosLayout.setHorizontalGroup(
            panel_movimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
            .addGroup(panel_movimientosLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_movimientosLayout.setVerticalGroup(
            panel_movimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_movimientosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lbl_nombre_cliente.setText("txtNombre_cliente");

        lbl_numero_cuenta.setText("lblNumero_cuenta");

        lblSaldo.setForeground(new java.awt.Color(146, 146, 146));
        lblSaldo.setText("Saldo");

        txt_sado.setEditable(false);
        txt_sado.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        txt_sado.setForeground(new java.awt.Color(255, 101, 0));
        txt_sado.setText("1000");

        jLabel1.setText("Sucursal:");

        lbl_sucursal.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbl_sucursal.setForeground(new java.awt.Color(247, 17, 56));
        lbl_sucursal.setText("los olivos");
        lbl_sucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_sucursalMouseClicked(evt);
            }
        });

        lbl_direcion.setText("Lima");

        jMenu1.setText("File");

        jMenuItem1.setText("Cerrar");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Operaciones");

        jMenuItem2.setText("Depositar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Retirar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSaldo)
                            .addComponent(txt_sado, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_numero_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_direcion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(16, 16, 16)))
                .addComponent(panel_movimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_movimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_numero_cuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_direcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_sado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_sucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_sucursalMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, cuenta.getSucursal().getDireccion(), "Direcion Sucursal", 1);
    }//GEN-LAST:event_lbl_sucursalMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    //retirar
        FormOperacion op=new FormOperacion(this);
        op.setdatos(pcuenta,"Retiro",true);
        op.setLocationRelativeTo(this);
        op.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FormOperacion op=new FormOperacion(this);
        op.setdatos(pcuenta,"Deposito",true);
        op.setLocationRelativeTo(this);
        op.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lbl_direcion;
    private javax.swing.JLabel lbl_nombre_cliente;
    private javax.swing.JLabel lbl_numero_cuenta;
    private javax.swing.JLabel lbl_sucursal;
    private javax.swing.JPanel panel_movimientos;
    private javax.swing.JScrollPane scrolPanel;
    private javax.swing.JTextField txt_sado;
    // End of variables declaration//GEN-END:variables
}
