/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.operaciones;

import entidades.ProxyCuenta;
import entidades.movimiento.Movimiento;
import java.awt.FlowLayout;
import java.net.Proxy;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import logica.Flogica;
import presentacion.FormOperacion;
import presentacion.Login;

/**
 *
 * @author aBriones
 */
public class FrmPrincipalCliente extends javax.swing.JFrame {

   
    ProxyCuenta pcuenta;
    ArrayList<Movimiento> movimientos;
    JPanel panel_list_movimientos;

    /**
     * Creates new form FrmPrincipalCliente
     */
    public FrmPrincipalCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setLayout(null);
        panel_list_movimientos = new JPanel(new FlowLayout(FlowLayout.LEFT));
        panel_list_movimientos.setLayout(new BoxLayout(panel_list_movimientos, BoxLayout.Y_AXIS));
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    public void set_datos(ProxyCuenta pcuenta) {
        this.panel_list_movimientos.removeAll();        
        this.pcuenta=pcuenta;        
        this.lbl_nombre_cliente.setText(pcuenta.getCliente().getNombreCompleto());
        this.lbl_numero_cuenta.setText(pcuenta.getCodigo());
        this.txt_sado.setText(pcuenta.getSaldo() + " " + pcuenta.getMoneda().getDescripcion());
        this.lbl_sucursal.setText(pcuenta.getSucursal().getNombre());
        this.lbl_direcion.setText(pcuenta.getSucursal().getCiudad());
        movimientos = pcuenta.getMovimientos();
        Collections.reverse(movimientos);
        Iterator<Movimiento> itera = movimientos.iterator();        
        while (itera.hasNext()) {
            Movimiento movimiento = itera.next();
            String tipo = Flogica.getInstance().getMovimiento_descripcion(movimiento.getCodigo_tipo_movimiento());

            String signo = (tipo.compareTo("Retiro") == 0) ? "-" : "+";

            panel_list_movimientos.add(new PanelMovimiento(movimiento.getFecha(), movimiento.getImporte(), tipo, signo));
        }
        this.scrolPanel.setViewportView(panel_list_movimientos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nombre_cliente = new javax.swing.JLabel();
        lbl_numero_cuenta = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        txt_sado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbl_sucursal = new javax.swing.JLabel();
        lbl_direcion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        scrolPanel = new javax.swing.JScrollPane();
        panel_movimientos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(655, 540));
        setPreferredSize(new java.awt.Dimension(575, 540));
        getContentPane().setLayout(null);

        lbl_nombre_cliente.setText("txtNombre_cliente");
        getContentPane().add(lbl_nombre_cliente);
        lbl_nombre_cliente.setBounds(6, 58, 190, 18);

        lbl_numero_cuenta.setText("lblNumero_cuenta");
        getContentPane().add(lbl_numero_cuenta);
        lbl_numero_cuenta.setBounds(6, 82, 180, 16);

        lblSaldo.setForeground(new java.awt.Color(146, 146, 146));
        lblSaldo.setText("Saldo");
        getContentPane().add(lblSaldo);
        lblSaldo.setBounds(6, 391, 32, 16);

        txt_sado.setEditable(false);
        txt_sado.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        txt_sado.setForeground(new java.awt.Color(255, 101, 0));
        txt_sado.setText("1000");
        getContentPane().add(txt_sado);
        txt_sado.setBounds(6, 413, 359, 40);

        jLabel1.setText("Sucursal:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 40, 54, 16);

        lbl_sucursal.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbl_sucursal.setForeground(new java.awt.Color(247, 17, 56));
        lbl_sucursal.setText("los olivos");
        lbl_sucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_sucursalMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_sucursal);
        lbl_sucursal.setBounds(220, 60, 120, 27);

        lbl_direcion.setText("Lima");
        getContentPane().add(lbl_direcion);
        lbl_direcion.setBounds(220, 90, 90, 16);

        jLabel3.setText("Hola");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 36, 180, 16);

        javax.swing.GroupLayout panel_movimientosLayout = new javax.swing.GroupLayout(panel_movimientos);
        panel_movimientos.setLayout(panel_movimientosLayout);
        panel_movimientosLayout.setHorizontalGroup(
            panel_movimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        panel_movimientosLayout.setVerticalGroup(
            panel_movimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        scrolPanel.setViewportView(panel_movimientos);

        getContentPane().add(scrolPanel);
        scrolPanel.setBounds(380, 40, 270, 479);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("Histoiral de movimientos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 10, 194, 24);

        jMenu1.setText("File");

        jMenuItem1.setText("Cerrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Operaciones");

        jMenuItem2.setText("Depositar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Retirar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_sucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_sucursalMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, pcuenta.getSucursal().getDireccion(), "Direcion Sucursal", 1);
    }//GEN-LAST:event_lbl_sucursalMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    //retirar
        FormOperacion op=new FormOperacion(this);
        op.setdatos(pcuenta,"Retiro",true);
        op.setLocationRelativeTo(this);
        op.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FormOperacion op=new FormOperacion(this);
        op.setdatos(pcuenta,"Deposito",true);
        op.setLocationRelativeTo(this);
        op.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
            Login login=new Login();
            login.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lbl_direcion;
    private javax.swing.JLabel lbl_nombre_cliente;
    private javax.swing.JLabel lbl_numero_cuenta;
    private javax.swing.JLabel lbl_sucursal;
    private javax.swing.JPanel panel_movimientos;
    private javax.swing.JScrollPane scrolPanel;
    private javax.swing.JTextField txt_sado;
    // End of variables declaration//GEN-END:variables
}
